const baseFields = [
    { name: "name", label: "Name", required: true },
    { name: "mindbody_id", label: "MindBody ID" },
    { name: "mindbody_name", label: "MindBody Name" },
    { name: "normalized_name", label: "Normalized Name" },
    { name: "description", label: "Description", multiline: true },
    { name: "active", label: "Active", type: "boolean" },
];

const siteScopedFields = [
    { name: "site", label: "Site", type: "site", required: true },
    ...baseFields,
];

export const dataResources = {
    sites: {
        label: "Sites",
        singular: "Site",
        endpoint: "sites",
        columns: [
            { label: "Name", field: "name" },
            { label: "Country", field: "country_code" },
            { label: "MindBody Site ID", field: "mindbody_site_id" },
            { label: "Active", field: "active" },
        ],
        fields: [
            { name: "name", label: "Name", required: true },
            {
                name: "country_code",
                label: "Country",
                type: "select",
                required: true,
                options: [
                    { value: "DO", label: "Dominican Republic" },
                    { value: "ES", label: "Spain" },
                ],
            },
            { name: "mindbody_site_id", label: "MindBody Site ID" },
            { name: "description", label: "Description", multiline: true },
            { name: "active", label: "Active", type: "boolean" },
        ],
    },
    studios: {
        label: "Studios",
        singular: "Studio",
        endpoint: "studios",
        columns: [
            { label: "Name", field: "name" },
            { label: "Site", field: "site_name" },
            { label: "MindBody Name", field: "mindbody_name" },
            { label: "Active", field: "active" },
        ],
        fields: siteScopedFields,
    },
    rooms: {
        label: "Rooms",
        singular: "Room",
        endpoint: "rooms",
        columns: [
            { label: "Name", field: "name" },
            { label: "Site", field: "site_name" },
            { label: "Studio", field: "studio_name" },
            { label: "Room Type", field: "room_type" },
            { label: "Group Capacity", field: "group_capacity" },
            { label: "Private Capacity", field: "private_capacity" },
            { label: "Active", field: "active" },
        ],
        fields: [
            ...siteScopedFields,
            { name: "studio", label: "Studio", type: "studio", required: true },
            {
                name: "room_type",
                label: "Room Type",
                type: "select",
                required: true,
                options: [
                    { value: "group", label: "Group" },
                    { value: "private", label: "Private" },
                    { value: "mixed", label: "Mixed" },
                ],
            },
            { name: "group_capacity", label: "Group Capacity", type: "number", default: 0 },
            { name: "private_capacity", label: "Private Capacity", type: "number", default: 0 },
        ],
    },
    clients: {
        label: "Clients",
        singular: "Client",
        endpoint: "clients",
        columns: [
            { label: "Name", field: "name" },
            { label: "First Name", field: "first_name" },
            { label: "Last Name", field: "last_name" },
            { label: "Site", field: "site_name" },
            { label: "MindBody ID", field: "mindbody_id" },
            { label: "Email", field: "email" },
            { label: "Phone", field: "phone" },
            { label: "Active", field: "active" },
        ],
        fields: [
            ...siteScopedFields,
            { name: "first_name", label: "First Name" },
            { name: "last_name", label: "Last Name" },
            { name: "email", label: "Email", type: "email" },
            { name: "phone", label: "Phone" },
        ],
    },
    "staff-members": {
        label: "Staff",
        singular: "Staff Member",
        endpoint: "staff-members",
        columns: [
            { label: "Name", field: "name" },
            { label: "First Name", field: "first_name" },
            { label: "Last Name", field: "last_name" },
            { label: "Site", field: "site_name" },
            { label: "MindBody Name", field: "mindbody_name" },
            { label: "Active", field: "active" },
        ],
        fields: [
            ...siteScopedFields,
            { name: "first_name", label: "First Name" },
            { name: "last_name", label: "Last Name" },
        ],
    },
    "service-categories": {
        label: "Service Categories",
        singular: "Service Category",
        endpoint: "service-categories",
        columns: [
            { label: "Name", field: "name" },
            { label: "Site", field: "site_name" },
            { label: "MindBody Name", field: "mindbody_name" },
            { label: "Active", field: "active" },
        ],
        fields: siteScopedFields,
    },
    "pricing-options": {
        label: "Pricing Options",
        singular: "Pricing Option",
        endpoint: "pricing-options",
        columns: [
            { label: "Name", field: "name" },
            { label: "Site", field: "site_name" },
            { label: "Service Category", field: "service_category_name" },
            { label: "MindBody Name", field: "mindbody_name" },
            { label: "Track Retention", field: "track_retention" },
            { label: "Active", field: "active" },
        ],
        fields: [
            ...siteScopedFields,
            { name: "service_category", label: "Service Category", type: "serviceCategory" },
            { name: "track_retention", label: "Track Retention", type: "boolean", default: false },
        ],
    },
    "payment-methods": {
        label: "Payment Methods",
        singular: "Payment Method",
        endpoint: "payment-methods",
        columns: [
            { label: "Name", field: "name" },
            { label: "Site", field: "site_name" },
            { label: "MindBody Name", field: "mindbody_name" },
            { label: "Active", field: "active" },
        ],
        fields: siteScopedFields,
    },
    "scheduled-classes": {
        label: "Scheduled Classes",
        singular: "Scheduled Class",
        endpoint: "scheduled-classes",
        columns: [
            { label: "Date", field: "class_date" },
            { label: "Start", field: "start_time" },
            { label: "Name", field: "name" },
            { label: "Site", field: "site_name" },
            { label: "Studio", field: "studio_name" },
            { label: "Room", field: "room_name" },
            { label: "Type", field: "session_type" },
            { label: "Capacity", field: "capacity" },
            { label: "Status", field: "status" },
            { label: "Reason", field: "reason" },
        ],
        fields: [
            { name: "site", label: "Site", type: "site", required: true },
            { name: "studio", label: "Studio", type: "studio", required: true },
            { name: "room", label: "Room", type: "room" },
            { name: "staff_member", label: "Instructor", type: "staffMember" },
            { name: "pricing_option", label: "Pricing Option", type: "pricingOption" },
            { name: "name", label: "Name", required: true },
            { name: "class_date", label: "Date", type: "date", required: true },
            { name: "start_time", label: "Start Time", type: "time", required: true },
            { name: "end_time", label: "End Time", type: "time", required: true },
            {
                name: "session_type",
                label: "Session Type",
                type: "select",
                required: true,
                options: [
                    { value: "group", label: "Group" },
                    { value: "private", label: "Private" },
                ],
            },
            { name: "capacity", label: "Capacity", type: "number", default: 0 },
            {
                name: "status",
                label: "Status",
                type: "select",
                required: true,
                options: [
                    { value: "scheduled", label: "Scheduled" },
                    { value: "cancelled", label: "Cancelled" },
                    { value: "unavailable", label: "Unavailable" },
                    { value: "needs_review", label: "Needs Review" },
                    { value: "conflict", label: "Conflict" },
                ],
            },
            { name: "reason", label: "Reason" },
            { name: "notes", label: "Notes", multiline: true },
        ],
    },
    "studio-closures": {
        label: "Closures",
        singular: "Closure",
        endpoint: "studio-closures",
        columns: [
            { label: "Date", field: "closure_date" },
            { label: "Site", field: "site_name" },
            { label: "Studio", field: "studio_name" },
            { label: "Room", field: "room_name" },
            { label: "All Day", field: "all_day" },
            { label: "Start", field: "start_time" },
            { label: "End", field: "end_time" },
            { label: "Reason", field: "reason" },
            { label: "Active", field: "active" },
        ],
        fields: [
            { name: "site", label: "Site", type: "site", required: true },
            { name: "studio", label: "Studio", type: "studio" },
            { name: "room", label: "Room", type: "room" },
            { name: "closure_date", label: "Date", type: "date", required: true },
            { name: "all_day", label: "All Day", type: "boolean", default: true },
            { name: "start_time", label: "Start Time", type: "time" },
            { name: "end_time", label: "End Time", type: "time" },
            { name: "reason", label: "Reason", required: true },
            { name: "active", label: "Active", type: "boolean" },
        ],
    },
};

export const dataResourceList = Object.entries(dataResources).map(([key, value]) => ({
    key,
    ...value,
}));
