export const importedResources = {
    "attendance-visits": {
        label: "Attendance Visits",
        endpoint: "attendance-visits",
        dateLabel: "Visit Date",
        columns: [
            { label: "Date", field: "visit_date" },
            { label: "Time", field: "visit_time_raw" },
            { label: "Client", field: "client_name" },
            { label: "Client ID", field: "client_mindbody_id" },
            { label: "Studio", field: "visit_studio_name" },
            { label: "Instructor", field: "staff_member_name" },
            { label: "Service", field: "pricing_option_name" },
            { label: "Payment", field: "payment_method_name" },
            { label: "Revenue", field: "revenue", type: "money" },
            { label: "Late Cancel", field: "late_cancel", type: "boolean" },
            { label: "No Show", field: "no_show", type: "boolean" },
        ],
    },
    "sale-lines": {
        label: "Sale Lines",
        endpoint: "sale-lines",
        dateLabel: "Sale Date",
        columns: [
            { label: "Date", field: "sale_date" },
            { label: "Sale #", field: "sale_number" },
            { label: "Client", field: "client_name" },
            { label: "Client ID", field: "client_mindbody_id" },
            { label: "Item", field: "item_name" },
            { label: "Studio", field: "studio_name" },
            { label: "Payment", field: "payment_method_name" },
            { label: "Quantity", field: "quantity" },
            { label: "Item Total", field: "item_total", type: "money" },
            { label: "Paid", field: "paid_total", type: "money" },
            { label: "Discount", field: "discount_amount", type: "money" },
        ],
    },
    "service-purchases": {
        label: "Service Purchases",
        endpoint: "service-purchases",
        dateLabel: "Sale Date",
        columns: [
            { label: "Sale Date", field: "sale_date" },
            { label: "Activation", field: "activation_date" },
            { label: "Expiration", field: "expiration_date" },
            { label: "Client", field: "client_name" },
            { label: "Client ID", field: "client_mindbody_id" },
            { label: "Service", field: "pricing_option_name" },
            { label: "Category", field: "service_category_name" },
            { label: "Total", field: "total_amount", type: "money" },
            { label: "Cash Eq.", field: "cash_equivalent", type: "money" },
            { label: "Non Cash", field: "non_cash_equivalent", type: "money" },
            { label: "Quantity", field: "quantity" },
        ],
    },
    "report-imports": {
        label: "Import History",
        endpoint: "report-imports",
        hideDateFilters: true,
        columns: [
            { label: "Uploaded", field: "uploaded_at", type: "datetime" },
            { label: "Report Type", field: "report_type" },
            { label: "File", field: "file_name" },
            { label: "Status", field: "status" },
            { label: "Rows", field: "total_rows" },
            { label: "Valid", field: "valid_rows" },
            { label: "Errors", field: "error_rows" },
            { label: "Uploaded By", field: "uploaded_by_name" },
        ],
    },
    "attendance-raw-rows": {
        label: "Attendance Raw Rows",
        endpoint: "attendance-raw-rows",
        raw: true,
        columns: [
            { label: "Import", field: "report_import" },
            { label: "Row", field: "row_number" },
            { label: "Site", field: "site_name" },
            { label: "Valid", field: "is_valid", type: "boolean" },
            { label: "Errors", field: "validation_errors", type: "list" },
            { label: "Summary", field: "payload_summary" },
        ],
    },
    "sale-raw-rows": {
        label: "Sales Raw Rows",
        endpoint: "sale-raw-rows",
        raw: true,
        columns: [
            { label: "Import", field: "report_import" },
            { label: "Row", field: "row_number" },
            { label: "Site", field: "site_name" },
            { label: "Valid", field: "is_valid", type: "boolean" },
            { label: "Errors", field: "validation_errors", type: "list" },
            { label: "Summary", field: "payload_summary" },
        ],
    },
    "service-purchase-raw-rows": {
        label: "Service Purchase Raw Rows",
        endpoint: "service-purchase-raw-rows",
        raw: true,
        columns: [
            { label: "Import", field: "report_import" },
            { label: "Row", field: "row_number" },
            { label: "Site", field: "site_name" },
            { label: "Valid", field: "is_valid", type: "boolean" },
            { label: "Errors", field: "validation_errors", type: "list" },
            { label: "Summary", field: "payload_summary" },
        ],
    },
};

export const importedResourceList = Object.entries(importedResources).map(([key, value]) => ({
    key,
    ...value,
}));
